# =====================================================
# inventory-service base configuration
# Served by Config Server at: /inventory-service/default
# =====================================================

server:
  port: 8084

spring:
  application:
    name: inventory-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
