# =====================================================
# product-service base configuration
# Served by Config Server at: /product-service/default
# =====================================================

server:
  port: 8083

spring:
  application:
    name: product-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
